//! The option records' metadata (HighsOptions.h: names, types, descriptions,
//! bounds and defaults), generated from a C++ HighsOptions by
//! rust/bench/gen_option_records.cpp; a test checks the defaults against
//! `Opts`. Crest's options API works on these (the C++ builds use their own
//! records).

use super::options::{BOOL, DOUBLE, INT, STRING};

/// An option record's metadata
pub struct Meta {
    pub type_: i32,
    pub advanced: bool,
    pub name: &'static str,
    pub description: &'static str,
    pub bool_default: bool,
    pub int: (i32, i32, i32),
    pub dbl: (f64, f64, f64),
    pub str_default: &'static str,
}

/// HighsOptions::records' metadata, in their order
pub const RECORDS: &[Meta] = &[
    Meta {
        type_: STRING,
        advanced: false,
        name: "presolve",
        description: "Presolve: \"off\", \"choose\" or \"on\"",
        bool_default: false,
        int: (0, 0, 0),
        dbl: (0.0, 0.0, 0.0),
        str_default: "choose",
    },
    Meta {
        type_: STRING,
        advanced: false,
        name: "solver",
        description: "LP/QP solver: \"choose\", \"simplex\", \"ipm\", \"ipx\", \"hipo\", \"pdlp\", \"qpasm\" or \"hipdlp\", ",
        bool_default: false,
        int: (0, 0, 0),
        dbl: (0.0, 0.0, 0.0),
        str_default: "choose",
    },
    Meta {
        type_: STRING,
        advanced: false,
        name: "parallel",
        description: "Parallel: \"off\", \"choose\" or \"on\"",
        bool_default: false,
        int: (0, 0, 0),
        dbl: (0.0, 0.0, 0.0),
        str_default: "choose",
    },
    Meta {
        type_: INT,
        advanced: false,
        name: "threads",
        description: "Maximum number of threads used by HiGHS (0: automatic)",
        bool_default: false,
        int: (0, 0, 2147483647),
        dbl: (0.0, 0.0, 0.0),
        str_default: "",
    },
    Meta {
        type_: STRING,
        advanced: false,
        name: "run_crossover",
        description: "Run IPM crossover: \"off\", \"choose\" or \"on\"",
        bool_default: false,
        int: (0, 0, 0),
        dbl: (0.0, 0.0, 0.0),
        str_default: "on",
    },
    Meta {
        type_: DOUBLE,
        advanced: false,
        name: "time_limit",
        description: "Time limit (seconds)",
        bool_default: false,
        int: (0, 0, 0),
        dbl: (0.0, f64::INFINITY, f64::INFINITY),
        str_default: "",
    },
    Meta {
        type_: STRING,
        advanced: false,
        name: "ranging",
        description: "Compute cost, bound, RHS and basic solution ranging: \"off\" or \"on\"",
        bool_default: false,
        int: (0, 0, 0),
        dbl: (0.0, 0.0, 0.0),
        str_default: "off",
    },
    Meta {
        type_: DOUBLE,
        advanced: false,
        name: "infinite_cost",
        description: "Limit on |cost coefficient|: values greater than or equal to this will be treated as infinite",
        bool_default: false,
        int: (0, 0, 0),
        dbl: (1000000000000000.0, 1e+20, f64::INFINITY),
        str_default: "",
    },
    Meta {
        type_: DOUBLE,
        advanced: false,
        name: "infinite_bound",
        description: "Limit on |constraint bound|: values greater than or equal to this will be treated as infinite",
        bool_default: false,
        int: (0, 0, 0),
        dbl: (1000000000000000.0, 1e+20, f64::INFINITY),
        str_default: "",
    },
    Meta {
        type_: DOUBLE,
        advanced: false,
        name: "small_matrix_value",
        description: "Lower limit on |matrix entries|: values less than or equal to this will be treated as zero",
        bool_default: false,
        int: (0, 0, 0),
        dbl: (9.9999999999999998e-13, 1.0000000000000001e-09, f64::INFINITY),
        str_default: "",
    },
    Meta {
        type_: DOUBLE,
        advanced: false,
        name: "large_matrix_value",
        description: "Upper limit on |matrix entries|: values greater than or equal to this will be treated as infinite",
        bool_default: false,
        int: (0, 0, 0),
        dbl: (1.0, 1000000000000000.0, f64::INFINITY),
        str_default: "",
    },
    Meta {
        type_: DOUBLE,
        advanced: false,
        name: "kkt_tolerance",
        description: "If changed from its default value, this tolerance is used for all feasibility and optimality (KKT) measures",
        bool_default: false,
        int: (0, 0, 0),
        dbl: (1e-10, 9.9999999999999995e-08, f64::INFINITY),
        str_default: "",
    },
    Meta {
        type_: DOUBLE,
        advanced: false,
        name: "primal_feasibility_tolerance",
        description: "Primal feasibility tolerance",
        bool_default: false,
        int: (0, 0, 0),
        dbl: (1e-10, 9.9999999999999995e-08, f64::INFINITY),
        str_default: "",
    },
    Meta {
        type_: DOUBLE,
        advanced: false,
        name: "dual_feasibility_tolerance",
        description: "Dual feasibility tolerance",
        bool_default: false,
        int: (0, 0, 0),
        dbl: (1e-10, 9.9999999999999995e-08, f64::INFINITY),
        str_default: "",
    },
    Meta {
        type_: DOUBLE,
        advanced: false,
        name: "primal_residual_tolerance",
        description: "Primal residual tolerance",
        bool_default: false,
        int: (0, 0, 0),
        dbl: (1e-10, 9.9999999999999995e-08, f64::INFINITY),
        str_default: "",
    },
    Meta {
        type_: DOUBLE,
        advanced: false,
        name: "dual_residual_tolerance",
        description: "Dual residual tolerance",
        bool_default: false,
        int: (0, 0, 0),
        dbl: (1e-10, 9.9999999999999995e-08, f64::INFINITY),
        str_default: "",
    },
    Meta {
        type_: DOUBLE,
        advanced: false,
        name: "optimality_tolerance",
        description: "Optimality tolerance",
        bool_default: false,
        int: (0, 0, 0),
        dbl: (1e-10, 9.9999999999999995e-08, f64::INFINITY),
        str_default: "",
    },
    Meta {
        type_: DOUBLE,
        advanced: false,
        name: "objective_bound",
        description: "Objective bound for termination of the dual simplex solver",
        bool_default: false,
        int: (0, 0, 0),
        dbl: (f64::NEG_INFINITY, f64::INFINITY, f64::INFINITY),
        str_default: "",
    },
    Meta {
        type_: DOUBLE,
        advanced: false,
        name: "objective_target",
        description: "Objective target for termination of the MIP solver",
        bool_default: false,
        int: (0, 0, 0),
        dbl: (f64::NEG_INFINITY, f64::NEG_INFINITY, f64::INFINITY),
        str_default: "",
    },
    Meta {
        type_: INT,
        advanced: false,
        name: "random_seed",
        description: "Random seed used in HiGHS",
        bool_default: false,
        int: (0, 0, 2147483647),
        dbl: (0.0, 0.0, 0.0),
        str_default: "",
    },
    Meta {
        type_: INT,
        advanced: false,
        name: "user_objective_scale",
        description: "Exponent of power-of-two objective scaling for model",
        bool_default: false,
        int: (-2147483647, 0, 2147483647),
        dbl: (0.0, 0.0, 0.0),
        str_default: "",
    },
    Meta {
        type_: INT,
        advanced: false,
        name: "user_bound_scale",
        description: "Exponent of power-of-two bound scaling for model",
        bool_default: false,
        int: (-2147483647, 0, 2147483647),
        dbl: (0.0, 0.0, 0.0),
        str_default: "",
    },
    Meta {
        type_: INT,
        advanced: true,
        name: "highs_debug_level",
        description: "Debugging level in HiGHS",
        bool_default: false,
        int: (0, 0, 3),
        dbl: (0.0, 0.0, 0.0),
        str_default: "",
    },
    Meta {
        type_: INT,
        advanced: true,
        name: "highs_analysis_level",
        description: "Analysis level in HiGHS",
        bool_default: false,
        int: (0, 0, 511),
        dbl: (0.0, 0.0, 0.0),
        str_default: "",
    },
    Meta {
        type_: INT,
        advanced: false,
        name: "simplex_strategy",
        description: "Strategy for simplex solver 0 => Choose; 1 => Dual (serial); 2 => Dual (SIP); 3 => Dual (PAMI); 4 => Primal",
        bool_default: false,
        int: (0, 1, 4),
        dbl: (0.0, 0.0, 0.0),
        str_default: "",
    },
    Meta {
        type_: INT,
        advanced: false,
        name: "simplex_scale_strategy",
        description: "Simplex scaling strategy: off / choose / equilibration (default) / forced equilibration / max value (0/1/2/3/4)",
        bool_default: false,
        int: (0, 2, 4),
        dbl: (0.0, 0.0, 0.0),
        str_default: "",
    },
    Meta {
        type_: INT,
        advanced: true,
        name: "simplex_crash_strategy",
        description: "Strategy for simplex crash: off / LTSSF / Bixby (0/1/2)",
        bool_default: false,
        int: (0, 0, 9),
        dbl: (0.0, 0.0, 0.0),
        str_default: "",
    },
    Meta {
        type_: INT,
        advanced: false,
        name: "simplex_dual_edge_weight_strategy",
        description: "Strategy for simplex dual edge weights: Choose / Dantzig / Devex / Steepest Edge (-1/0/1/2)",
        bool_default: false,
        int: (-1, -1, 2),
        dbl: (0.0, 0.0, 0.0),
        str_default: "",
    },
    Meta {
        type_: INT,
        advanced: false,
        name: "simplex_primal_edge_weight_strategy",
        description: "Strategy for simplex primal edge weights: Choose / Dantzig / Devex / Steepest Edge (-1/0/1/2)",
        bool_default: false,
        int: (-1, -1, 2),
        dbl: (0.0, 0.0, 0.0),
        str_default: "",
    },
    Meta {
        type_: INT,
        advanced: false,
        name: "simplex_iteration_limit",
        description: "Iteration limit for simplex solver when solving LPs, but not subproblems in the MIP solver",
        bool_default: false,
        int: (0, 2147483647, 2147483647),
        dbl: (0.0, 0.0, 0.0),
        str_default: "",
    },
    Meta {
        type_: INT,
        advanced: false,
        name: "simplex_update_limit",
        description: "Limit on the number of simplex UPDATE operations",
        bool_default: false,
        int: (0, 5000, 2147483647),
        dbl: (0.0, 0.0, 0.0),
        str_default: "",
    },
    Meta {
        type_: INT,
        advanced: true,
        name: "simplex_min_concurrency",
        description: "Minimum level of concurrency in parallel simplex",
        bool_default: false,
        int: (1, 1, 8),
        dbl: (0.0, 0.0, 0.0),
        str_default: "",
    },
    Meta {
        type_: INT,
        advanced: false,
        name: "simplex_max_concurrency",
        description: "Maximum level of concurrency in parallel simplex",
        bool_default: false,
        int: (1, 8, 8),
        dbl: (0.0, 0.0, 0.0),
        str_default: "",
    },
    Meta {
        type_: BOOL,
        advanced: false,
        name: "output_flag",
        description: "Enables or disables solver output",
        bool_default: true,
        int: (0, 0, 0),
        dbl: (0.0, 0.0, 0.0),
        str_default: "",
    },
    Meta {
        type_: BOOL,
        advanced: false,
        name: "log_to_console",
        description: "Enables or disables console logging",
        bool_default: true,
        int: (0, 0, 0),
        dbl: (0.0, 0.0, 0.0),
        str_default: "",
    },
    Meta {
        type_: BOOL,
        advanced: true,
        name: "timeless_log",
        description: "Suppression of time-based data in logging",
        bool_default: false,
        int: (0, 0, 0),
        dbl: (0.0, 0.0, 0.0),
        str_default: "",
    },
    Meta {
        type_: STRING,
        advanced: false,
        name: "log_file",
        description: "Log file",
        bool_default: false,
        int: (0, 0, 0),
        dbl: (0.0, 0.0, 0.0),
        str_default: "",
    },
    Meta {
        type_: BOOL,
        advanced: false,
        name: "write_model_to_file",
        description: "Write the model to a file",
        bool_default: false,
        int: (0, 0, 0),
        dbl: (0.0, 0.0, 0.0),
        str_default: "",
    },
    Meta {
        type_: BOOL,
        advanced: false,
        name: "write_presolved_model_to_file",
        description: "Write the presolved model to a file",
        bool_default: false,
        int: (0, 0, 0),
        dbl: (0.0, 0.0, 0.0),
        str_default: "",
    },
    Meta {
        type_: BOOL,
        advanced: false,
        name: "write_solution_to_file",
        description: "Write the primal and dual solution to a file",
        bool_default: false,
        int: (0, 0, 0),
        dbl: (0.0, 0.0, 0.0),
        str_default: "",
    },
    Meta {
        type_: INT,
        advanced: false,
        name: "write_solution_style",
        description: "Style of solution file (raw = computer-readable, pretty = human-readable): -1 => HiGHS old raw (deprecated); 0 => HiGHS raw; 1 => HiGHS pretty; 2 => Glpsol raw; 3 => Glpsol pretty; 4 => HiGHS sparse raw",
        bool_default: false,
        int: (-1, 0, 4),
        dbl: (0.0, 0.0, 0.0),
        str_default: "",
    },
    Meta {
        type_: INT,
        advanced: false,
        name: "glpsol_cost_row_location",
        description: "Location of cost row for Glpsol file: -2 => Last; -1 => None; 0 => None if empty, otherwise data file location; 1 <= n <= num_row => Location n; n > num_row => Last",
        bool_default: false,
        int: (-2, 0, 2147483647),
        dbl: (0.0, 0.0, 0.0),
        str_default: "",
    },
    Meta {
        type_: BOOL,
        advanced: true,
        name: "icrash",
        description: "Run iCrash",
        bool_default: false,
        int: (0, 0, 0),
        dbl: (0.0, 0.0, 0.0),
        str_default: "",
    },
    Meta {
        type_: BOOL,
        advanced: true,
        name: "icrash_dualize",
        description: "Dualize strategy for iCrash",
        bool_default: false,
        int: (0, 0, 0),
        dbl: (0.0, 0.0, 0.0),
        str_default: "",
    },
    Meta {
        type_: STRING,
        advanced: true,
        name: "icrash_strategy",
        description: "Strategy for iCrash",
        bool_default: false,
        int: (0, 0, 0),
        dbl: (0.0, 0.0, 0.0),
        str_default: "ICA",
    },
    Meta {
        type_: DOUBLE,
        advanced: true,
        name: "icrash_starting_weight",
        description: "iCrash starting weight",
        bool_default: false,
        int: (0, 0, 0),
        dbl: (1e-10, 0.001, 1.0000000000000001e+50),
        str_default: "",
    },
    Meta {
        type_: INT,
        advanced: true,
        name: "icrash_iterations",
        description: "iCrash iterations",
        bool_default: false,
        int: (0, 30, 200),
        dbl: (0.0, 0.0, 0.0),
        str_default: "",
    },
    Meta {
        type_: INT,
        advanced: true,
        name: "icrash_approx_iter",
        description: "iCrash approximate minimization iterations",
        bool_default: false,
        int: (0, 50, 100),
        dbl: (0.0, 0.0, 0.0),
        str_default: "",
    },
    Meta {
        type_: BOOL,
        advanced: true,
        name: "icrash_exact",
        description: "Exact subproblem solution for iCrash",
        bool_default: false,
        int: (0, 0, 0),
        dbl: (0.0, 0.0, 0.0),
        str_default: "",
    },
    Meta {
        type_: BOOL,
        advanced: true,
        name: "icrash_breakpoints",
        description: "Exact subproblem solution for iCrash",
        bool_default: false,
        int: (0, 0, 0),
        dbl: (0.0, 0.0, 0.0),
        str_default: "",
    },
    Meta {
        type_: STRING,
        advanced: false,
        name: "read_solution_file",
        description: "Read solution file",
        bool_default: false,
        int: (0, 0, 0),
        dbl: (0.0, 0.0, 0.0),
        str_default: "",
    },
    Meta {
        type_: STRING,
        advanced: false,
        name: "read_basis_file",
        description: "Read basis file",
        bool_default: false,
        int: (0, 0, 0),
        dbl: (0.0, 0.0, 0.0),
        str_default: "",
    },
    Meta {
        type_: STRING,
        advanced: false,
        name: "write_model_file",
        description: "Write model file",
        bool_default: false,
        int: (0, 0, 0),
        dbl: (0.0, 0.0, 0.0),
        str_default: "",
    },
    Meta {
        type_: STRING,
        advanced: false,
        name: "solution_file",
        description: "Write solution file",
        bool_default: false,
        int: (0, 0, 0),
        dbl: (0.0, 0.0, 0.0),
        str_default: "",
    },
    Meta {
        type_: STRING,
        advanced: false,
        name: "write_basis_file",
        description: "Write basis file",
        bool_default: false,
        int: (0, 0, 0),
        dbl: (0.0, 0.0, 0.0),
        str_default: "",
    },
    Meta {
        type_: STRING,
        advanced: false,
        name: "write_presolved_model_file",
        description: "Write presolved model file",
        bool_default: false,
        int: (0, 0, 0),
        dbl: (0.0, 0.0, 0.0),
        str_default: "",
    },
    Meta {
        type_: STRING,
        advanced: false,
        name: "write_iis_model_file",
        description: "Write IIS model file",
        bool_default: false,
        int: (0, 0, 0),
        dbl: (0.0, 0.0, 0.0),
        str_default: "",
    },
    Meta {
        type_: BOOL,
        advanced: false,
        name: "mip_detect_symmetry",
        description: "Whether MIP symmetry should be detected",
        bool_default: true,
        int: (0, 0, 0),
        dbl: (0.0, 0.0, 0.0),
        str_default: "",
    },
    Meta {
        type_: BOOL,
        advanced: false,
        name: "mip_allow_restart",
        description: "Whether MIP restart is permitted",
        bool_default: true,
        int: (0, 0, 0),
        dbl: (0.0, 0.0, 0.0),
        str_default: "",
    },
    Meta {
        type_: INT,
        advanced: false,
        name: "mip_max_nodes",
        description: "MIP solver max number of nodes",
        bool_default: false,
        int: (0, 2147483647, 2147483647),
        dbl: (0.0, 0.0, 0.0),
        str_default: "",
    },
    Meta {
        type_: INT,
        advanced: false,
        name: "mip_max_stall_nodes",
        description: "MIP solver max number of nodes where estimate is above cutoff bound",
        bool_default: false,
        int: (0, 2147483647, 2147483647),
        dbl: (0.0, 0.0, 0.0),
        str_default: "",
    },
    Meta {
        type_: INT,
        advanced: false,
        name: "mip_max_start_nodes",
        description: "MIP solver max number of nodes when completing a partial MIP start",
        bool_default: false,
        int: (0, 500, 2147483647),
        dbl: (0.0, 0.0, 0.0),
        str_default: "",
    },
    Meta {
        type_: BOOL,
        advanced: false,
        name: "mip_improving_solution_save",
        description: "Whether improving MIP solutions should be saved",
        bool_default: false,
        int: (0, 0, 0),
        dbl: (0.0, 0.0, 0.0),
        str_default: "",
    },
    Meta {
        type_: BOOL,
        advanced: false,
        name: "mip_improving_solution_report_sparse",
        description: "Whether improving MIP solutions should be reported in sparse format",
        bool_default: false,
        int: (0, 0, 0),
        dbl: (0.0, 0.0, 0.0),
        str_default: "",
    },
    Meta {
        type_: STRING,
        advanced: false,
        name: "mip_improving_solution_file",
        description: "File for reporting improving MIP solutions: not reported for an empty string \\\"\\\"",
        bool_default: false,
        int: (0, 0, 0),
        dbl: (0.0, 0.0, 0.0),
        str_default: "",
    },
    Meta {
        type_: BOOL,
        advanced: false,
        name: "mip_root_presolve_only",
        description: "Whether MIP presolve is only applied at the root node",
        bool_default: false,
        int: (0, 0, 0),
        dbl: (0.0, 0.0, 0.0),
        str_default: "",
    },
    Meta {
        type_: INT,
        advanced: false,
        name: "mip_lifting_for_probing",
        description: "Level of lifting for probing that is used",
        bool_default: false,
        int: (-1, -1, 2147483647),
        dbl: (0.0, 0.0, 0.0),
        str_default: "",
    },
    Meta {
        type_: INT,
        advanced: false,
        name: "mip_max_leaves",
        description: "MIP solver max number of leaf nodes",
        bool_default: false,
        int: (0, 2147483647, 2147483647),
        dbl: (0.0, 0.0, 0.0),
        str_default: "",
    },
    Meta {
        type_: INT,
        advanced: false,
        name: "mip_max_improving_sols",
        description: "Limit on the number of improving solutions found to stop the MIP solver prematurely",
        bool_default: false,
        int: (1, 2147483647, 2147483647),
        dbl: (0.0, 0.0, 0.0),
        str_default: "",
    },
    Meta {
        type_: INT,
        advanced: false,
        name: "mip_lp_age_limit",
        description: "Maximal age of dynamic LP rows before they are removed from the LP relaxation in the MIP solver",
        bool_default: false,
        int: (0, 10, 32767),
        dbl: (0.0, 0.0, 0.0),
        str_default: "",
    },
    Meta {
        type_: INT,
        advanced: false,
        name: "mip_pool_age_limit",
        description: "Maximal age of rows in the MIP solver cutpool before they are deleted",
        bool_default: false,
        int: (0, 30, 1000),
        dbl: (0.0, 0.0, 0.0),
        str_default: "",
    },
    Meta {
        type_: INT,
        advanced: false,
        name: "mip_pool_soft_limit",
        description: "Soft limit on the number of rows in the MIP solver cutpool for dynamic age adjustment",
        bool_default: false,
        int: (1, 10000, 2147483647),
        dbl: (0.0, 0.0, 0.0),
        str_default: "",
    },
    Meta {
        type_: INT,
        advanced: false,
        name: "mip_pscost_minreliable",
        description: "Minimal number of observations before MIP solver pseudo costs are considered reliable",
        bool_default: false,
        int: (0, 8, 2147483647),
        dbl: (0.0, 0.0, 0.0),
        str_default: "",
    },
    Meta {
        type_: INT,
        advanced: false,
        name: "mip_min_cliquetable_entries_for_parallelism",
        description: "Minimal number of entries in the MIP solver cliquetable before neighbourhood queries of the conflict graph use parallel processing",
        bool_default: false,
        int: (0, 100000, 2147483647),
        dbl: (0.0, 0.0, 0.0),
        str_default: "",
    },
    Meta {
        type_: INT,
        advanced: true,
        name: "mip_report_level",
        description: "MIP solver reporting level",
        bool_default: false,
        int: (0, 1, 2),
        dbl: (0.0, 0.0, 0.0),
        str_default: "",
    },
    Meta {
        type_: DOUBLE,
        advanced: false,
        name: "mip_feasibility_tolerance",
        description: "MIP integrality tolerance",
        bool_default: false,
        int: (0, 0, 0),
        dbl: (1e-10, 9.9999999999999995e-07, f64::INFINITY),
        str_default: "",
    },
    Meta {
        type_: DOUBLE,
        advanced: false,
        name: "mip_heuristic_effort",
        description: "Effort spent for MIP heuristics",
        bool_default: false,
        int: (0, 0, 0),
        dbl: (0.0, 0.050000000000000003, 1.0),
        str_default: "",
    },
    Meta {
        type_: BOOL,
        advanced: false,
        name: "mip_heuristic_run_feasibility_jump",
        description: "Use the feasibility jump heuristic",
        bool_default: true,
        int: (0, 0, 0),
        dbl: (0.0, 0.0, 0.0),
        str_default: "",
    },
    Meta {
        type_: BOOL,
        advanced: false,
        name: "mip_heuristic_run_rins",
        description: "Use the RINS heuristic",
        bool_default: true,
        int: (0, 0, 0),
        dbl: (0.0, 0.0, 0.0),
        str_default: "",
    },
    Meta {
        type_: BOOL,
        advanced: false,
        name: "mip_heuristic_run_rens",
        description: "Use the RENS heuristic",
        bool_default: true,
        int: (0, 0, 0),
        dbl: (0.0, 0.0, 0.0),
        str_default: "",
    },
    Meta {
        type_: BOOL,
        advanced: false,
        name: "mip_heuristic_run_graph_lns",
        description: "Use the graph-neighbourhood LNS heuristic (LP-guided dives on constraint-graph neighbourhoods) at the root",
        bool_default: true,
        int: (0, 0, 0),
        dbl: (0.0, 0.0, 0.0),
        str_default: "",
    },
    Meta {
        type_: BOOL,
        advanced: false,
        name: "mip_concurrent_helper",
        description: "Whether, when graph LNS runs, to use a second thread (unless threads is 1) to race IPX against the dual simplex on the first root LP and to run graph LNS alongside the MIP solver: this makes the solve non-deterministic",
        bool_default: true,
        int: (0, 0, 0),
        dbl: (0.0, 0.0, 0.0),
        str_default: "",
    },
    Meta {
        type_: BOOL,
        advanced: false,
        name: "mip_concurrent_crossover",
        description: "Whether the concurrent LNS helper and the MIP solver search independently until the helper crosses its solution with the MIP solver's (a better solution at the time limit where the gap cannot be closed, at the cost of a slower solve where it can)",
        bool_default: false,
        int: (0, 0, 0),
        dbl: (0.0, 0.0, 0.0),
        str_default: "",
    },
    Meta {
        type_: BOOL,
        advanced: false,
        name: "mip_heuristic_run_root_reduced_cost",
        description: "Use the rootReducedCost heuristic",
        bool_default: true,
        int: (0, 0, 0),
        dbl: (0.0, 0.0, 0.0),
        str_default: "",
    },
    Meta {
        type_: BOOL,
        advanced: false,
        name: "mip_heuristic_run_zi_round",
        description: "Use the ZI Round heuristic",
        bool_default: false,
        int: (0, 0, 0),
        dbl: (0.0, 0.0, 0.0),
        str_default: "",
    },
    Meta {
        type_: BOOL,
        advanced: false,
        name: "mip_heuristic_run_shifting",
        description: "Use the Shifting heuristic",
        bool_default: false,
        int: (0, 0, 0),
        dbl: (0.0, 0.0, 0.0),
        str_default: "",
    },
    Meta {
        type_: BOOL,
        advanced: false,
        name: "mip_allow_cut_separation_at_nodes",
        description: "Whether cut separation at nodes other than the root node is permitted",
        bool_default: true,
        int: (0, 0, 0),
        dbl: (0.0, 0.0, 0.0),
        str_default: "",
    },
    Meta {
        type_: DOUBLE,
        advanced: false,
        name: "mip_rel_gap",
        description: "Tolerance on relative gap, |ub-lb|/|ub|, to determine whether optimality has been reached for a MIP instance",
        bool_default: false,
        int: (0, 0, 0),
        dbl: (0.0, 0.0001, f64::INFINITY),
        str_default: "",
    },
    Meta {
        type_: DOUBLE,
        advanced: false,
        name: "mip_abs_gap",
        description: "Tolerance on absolute gap of MIP, |ub-lb|, to determine whether optimality has been reached for a MIP instance",
        bool_default: false,
        int: (0, 0, 0),
        dbl: (0.0, 9.9999999999999995e-07, f64::INFINITY),
        str_default: "",
    },
    Meta {
        type_: DOUBLE,
        advanced: false,
        name: "mip_min_logging_interval",
        description: "MIP minimum logging interval",
        bool_default: false,
        int: (0, 0, 0),
        dbl: (0.0, 5.0, f64::INFINITY),
        str_default: "",
    },
    Meta {
        type_: STRING,
        advanced: false,
        name: "mip_lp_solver",
        description: "MIP LP solver: \"choose\", \"simplex\", \"ipm\", \"ipx\" or \"hipo\"",
        bool_default: false,
        int: (0, 0, 0),
        dbl: (0.0, 0.0, 0.0),
        str_default: "choose",
    },
    Meta {
        type_: STRING,
        advanced: false,
        name: "mip_ipm_solver",
        description: "MIP IPM solver: \"choose\", \"ipx\" or \"hipo\"",
        bool_default: false,
        int: (0, 0, 0),
        dbl: (0.0, 0.0, 0.0),
        str_default: "choose",
    },
    Meta {
        type_: DOUBLE,
        advanced: false,
        name: "ipm_optimality_tolerance",
        description: "IPM optimality tolerance",
        bool_default: false,
        int: (0, 0, 0),
        dbl: (9.9999999999999998e-13, 1e-08, f64::INFINITY),
        str_default: "",
    },
    Meta {
        type_: BOOL,
        advanced: false,
        name: "mip_search_simulate_concurrency",
        description: "Simulate MIP search concurrency on a single thread",
        bool_default: false,
        int: (0, 0, 0),
        dbl: (0.0, 0.0, 0.0),
        str_default: "",
    },
    Meta {
        type_: INT,
        advanced: false,
        name: "ipm_iteration_limit",
        description: "Iteration limit for IPM solver",
        bool_default: false,
        int: (0, 2147483647, 2147483647),
        dbl: (0.0, 0.0, 0.0),
        str_default: "",
    },
    Meta {
        type_: STRING,
        advanced: false,
        name: "hipo_system",
        description: "HiPO Newton system: \"choose\", \"augmented\" or \"normaleq\"",
        bool_default: false,
        int: (0, 0, 0),
        dbl: (0.0, 0.0, 0.0),
        str_default: "choose",
    },
    Meta {
        type_: STRING,
        advanced: false,
        name: "hipo_parallel_type",
        description: "HiPO parallelism: \"tree\", \"node\" or \"both\"",
        bool_default: false,
        int: (0, 0, 0),
        dbl: (0.0, 0.0, 0.0),
        str_default: "both",
    },
    Meta {
        type_: STRING,
        advanced: false,
        name: "hipo_ordering",
        description: "HiPO matrix reordering: \"choose\", \"metis\", \"amd\" or \"rcm\"",
        bool_default: false,
        int: (0, 0, 0),
        dbl: (0.0, 0.0, 0.0),
        str_default: "choose",
    },
    Meta {
        type_: INT,
        advanced: false,
        name: "hipo_block_size",
        description: "Block size for dense linear algebra within HiPO",
        bool_default: false,
        int: (0, 128, 2147483647),
        dbl: (0.0, 0.0, 0.0),
        str_default: "",
    },
    Meta {
        type_: INT,
        advanced: false,
        name: "pdlp_iteration_limit",
        description: "Iteration limit for PDLP solver",
        bool_default: false,
        int: (0, 2147483647, 2147483647),
        dbl: (0.0, 0.0, 0.0),
        str_default: "",
    },
    Meta {
        type_: INT,
        advanced: false,
        name: "pdlp_scaling_mode",
        description: "Scaling mode for PDLP solver (default = 5): 1 => Ruiz; 2 => L2; 4 => PC",
        bool_default: false,
        int: (0, 5, 7),
        dbl: (0.0, 0.0, 0.0),
        str_default: "",
    },
    Meta {
        type_: INT,
        advanced: false,
        name: "pdlp_ruiz_iterations",
        description: "Number of Ruiz scaling iteraitons for PDLP solver",
        bool_default: false,
        int: (0, 10, 2147483647),
        dbl: (0.0, 0.0, 0.0),
        str_default: "",
    },
    Meta {
        type_: INT,
        advanced: false,
        name: "pdlp_restart_strategy",
        description: "Restart strategy for PDLP solver: 0 => off; 1 => fixed; 2 => adaptive; 3 => Halpern",
        bool_default: false,
        int: (0, 2, 3),
        dbl: (0.0, 0.0, 0.0),
        str_default: "",
    },
    Meta {
        type_: INT,
        advanced: false,
        name: "pdlp_cupdlpc_restart_method",
        description: "Restart mode for cuPDLP-C solver: 0 => none; 1 => GPU (default); 2 => CPU ",
        bool_default: false,
        int: (0, 1, 2),
        dbl: (0.0, 0.0, 0.0),
        str_default: "",
    },
    Meta {
        type_: INT,
        advanced: false,
        name: "pdlp_step_size_strategy",
        description: "Step size strategy for PDLP solver: 0 => fixed; 1 => adaptive; 2 => Malitsky-Pock; 3 => PID",
        bool_default: false,
        int: (0, 1, 3),
        dbl: (0.0, 0.0, 0.0),
        str_default: "",
    },
    Meta {
        type_: DOUBLE,
        advanced: false,
        name: "pdlp_optimality_tolerance",
        description: "PDLP optimality tolerance",
        bool_default: false,
        int: (0, 0, 0),
        dbl: (1e-10, 9.9999999999999995e-08, f64::INFINITY),
        str_default: "",
    },
    Meta {
        type_: BOOL,
        advanced: false,
        name: "qp_allow_hot_start",
        description: "Allow the active set QP solver to hot start",
        bool_default: false,
        int: (0, 0, 0),
        dbl: (0.0, 0.0, 0.0),
        str_default: "",
    },
    Meta {
        type_: INT,
        advanced: false,
        name: "qp_iteration_limit",
        description: "Iteration limit for the active set QP solver",
        bool_default: false,
        int: (0, 2147483647, 2147483647),
        dbl: (0.0, 0.0, 0.0),
        str_default: "",
    },
    Meta {
        type_: INT,
        advanced: false,
        name: "qp_nullspace_limit",
        description: "Nullspace limit for the active set QP solver",
        bool_default: false,
        int: (0, 4000, 2147483647),
        dbl: (0.0, 0.0, 0.0),
        str_default: "",
    },
    Meta {
        type_: DOUBLE,
        advanced: false,
        name: "qp_regularization_value",
        description: "Regularization value added to the Hessian in the active set QP solver",
        bool_default: false,
        int: (0, 0, 0),
        dbl: (0.0, 9.9999999999999995e-08, f64::INFINITY),
        str_default: "",
    },
    Meta {
        type_: INT,
        advanced: false,
        name: "iis_strategy",
        description: "Strategy for IIS calculation: 0 => Light test; 1 => Try dual ray; 2 => Try elastic LP; 4 => Prioritise columns; 8 => Find true IIS; 16 => Find relaxation IIS for MIP",
        bool_default: false,
        int: (0, 0, 31),
        dbl: (0.0, 0.0, 0.0),
        str_default: "",
    },
    Meta {
        type_: DOUBLE,
        advanced: false,
        name: "iis_time_limit",
        description: "Time limit for computing IIS (seconds)",
        bool_default: false,
        int: (0, 0, 0),
        dbl: (0.0, f64::INFINITY, f64::INFINITY),
        str_default: "",
    },
    Meta {
        type_: BOOL,
        advanced: false,
        name: "blend_multi_objectives",
        description: "Blend multiple objectives or apply lexicographically",
        bool_default: true,
        int: (0, 0, 0),
        dbl: (0.0, 0.0, 0.0),
        str_default: "",
    },
    Meta {
        type_: INT,
        advanced: true,
        name: "log_dev_level",
        description: "Output development messages: 0 => none; 1 => info; 2 => detailed; 3 => verbose",
        bool_default: false,
        int: (0, 0, 3),
        dbl: (0.0, 0.0, 0.0),
        str_default: "",
    },
    Meta {
        type_: BOOL,
        advanced: true,
        name: "log_githash",
        description: "Log the githash",
        bool_default: true,
        int: (0, 0, 0),
        dbl: (0.0, 0.0, 0.0),
        str_default: "",
    },
    Meta {
        type_: BOOL,
        advanced: true,
        name: "solve_relaxation",
        description: "Solve the relaxation of discrete model components",
        bool_default: false,
        int: (0, 0, 0),
        dbl: (0.0, 0.0, 0.0),
        str_default: "",
    },
    Meta {
        type_: BOOL,
        advanced: true,
        name: "allow_unbounded_or_infeasible",
        description: "Allow ModelStatus::kUnboundedOrInfeasible",
        bool_default: false,
        int: (0, 0, 0),
        dbl: (0.0, 0.0, 0.0),
        str_default: "",
    },
    Meta {
        type_: BOOL,
        advanced: true,
        name: "use_implied_bounds_from_presolve",
        description: "Use relaxed implied bounds from presolve",
        bool_default: false,
        int: (0, 0, 0),
        dbl: (0.0, 0.0, 0.0),
        str_default: "",
    },
    Meta {
        type_: BOOL,
        advanced: true,
        name: "lp_presolve_requires_basis_postsolve",
        description: "Prevents LP presolve steps for which postsolve cannot maintain a basis",
        bool_default: true,
        int: (0, 0, 0),
        dbl: (0.0, 0.0, 0.0),
        str_default: "",
    },
    Meta {
        type_: BOOL,
        advanced: true,
        name: "mps_parser_type_free",
        description: "Use the free format MPS file reader",
        bool_default: true,
        int: (0, 0, 0),
        dbl: (0.0, 0.0, 0.0),
        str_default: "",
    },
    Meta {
        type_: BOOL,
        advanced: true,
        name: "use_warm_start",
        description: "Use any warm start that is available",
        bool_default: true,
        int: (0, 0, 0),
        dbl: (0.0, 0.0, 0.0),
        str_default: "",
    },
    Meta {
        type_: BOOL,
        advanced: true,
        name: "write_matrix_image",
        description: "Write an image of the constraint matrix to a file",
        bool_default: false,
        int: (0, 0, 0),
        dbl: (0.0, 0.0, 0.0),
        str_default: "",
    },
    Meta {
        type_: BOOL,
        advanced: true,
        name: "write_hessian_image",
        description: "Write an image of the Hessian to a file",
        bool_default: false,
        int: (0, 0, 0),
        dbl: (0.0, 0.0, 0.0),
        str_default: "",
    },
    Meta {
        type_: INT,
        advanced: true,
        name: "keep_n_rows",
        description: "For multiple N-rows in MPS files: delete rows / delete entries / keep rows (-1/0/1)",
        bool_default: false,
        int: (-1, -1, 1),
        dbl: (0.0, 0.0, 0.0),
        str_default: "",
    },
    Meta {
        type_: INT,
        advanced: true,
        name: "cost_scale_factor",
        description: "Scaling factor for costs",
        bool_default: false,
        int: (-20, 0, 20),
        dbl: (0.0, 0.0, 0.0),
        str_default: "",
    },
    Meta {
        type_: INT,
        advanced: true,
        name: "allowed_matrix_scale_factor",
        description: "Largest power-of-two factor permitted when scaling the constraint matrix",
        bool_default: false,
        int: (0, 20, 30),
        dbl: (0.0, 0.0, 0.0),
        str_default: "",
    },
    Meta {
        type_: INT,
        advanced: true,
        name: "allowed_cost_scale_factor",
        description: "Largest power-of-two factor permitted when scaling the costs",
        bool_default: false,
        int: (0, 0, 20),
        dbl: (0.0, 0.0, 0.0),
        str_default: "",
    },
    Meta {
        type_: INT,
        advanced: true,
        name: "ipx_dualize_strategy",
        description: "Strategy for dualizing before IPX",
        bool_default: false,
        int: (-1, 2, 3),
        dbl: (0.0, 0.0, 0.0),
        str_default: "",
    },
    Meta {
        type_: INT,
        advanced: true,
        name: "simplex_dualize_strategy",
        description: "Strategy for dualizing before simplex",
        bool_default: false,
        int: (-1, -1, 1),
        dbl: (0.0, 0.0, 0.0),
        str_default: "",
    },
    Meta {
        type_: INT,
        advanced: true,
        name: "simplex_permute_strategy",
        description: "Strategy for permuting before simplex",
        bool_default: false,
        int: (-1, -1, 1),
        dbl: (0.0, 0.0, 0.0),
        str_default: "",
    },
    Meta {
        type_: INT,
        advanced: true,
        name: "max_dual_simplex_cleanup_level",
        description: "Max level of dual simplex cleanup",
        bool_default: false,
        int: (0, 1, 2147483647),
        dbl: (0.0, 0.0, 0.0),
        str_default: "",
    },
    Meta {
        type_: INT,
        advanced: true,
        name: "max_dual_simplex_phase1_cleanup_level",
        description: "Max level of dual simplex phase 1 cleanup",
        bool_default: false,
        int: (0, 2, 2147483647),
        dbl: (0.0, 0.0, 0.0),
        str_default: "",
    },
    Meta {
        type_: INT,
        advanced: true,
        name: "simplex_price_strategy",
        description: "Strategy for PRICE in simplex",
        bool_default: false,
        int: (0, 3, 3),
        dbl: (0.0, 0.0, 0.0),
        str_default: "",
    },
    Meta {
        type_: INT,
        advanced: true,
        name: "simplex_dse_exact_init_max_rows",
        description: "Max number of rows for which dual steepest edge weights of a non-logical basis are computed exactly; above it they are kept over LP changes that preserve them, or start from unit weights",
        bool_default: false,
        int: (0, 2147483647, 2147483647),
        dbl: (0.0, 0.0, 0.0),
        str_default: "",
    },
    Meta {
        type_: BOOL,
        advanced: true,
        name: "simplex_keep_random_vectors",
        description: "Whether to keep the random vectors of the simplex solver over re-solves of an LP of the same size, rather than drawing new ones for every solve (always the case above simplex_dse_exact_init_max_rows rows)",
        bool_default: false,
        int: (0, 0, 0),
        dbl: (0.0, 0.0, 0.0),
        str_default: "",
    },
    Meta {
        type_: BOOL,
        advanced: true,
        name: "full_lp_kkt_check",
        description: "Whether to assess all KKT measures of an LP solution with a basis (relative infeasibilities, complementarity violations, primal-dual objective error), rather than only its absolute primal and dual infeasibilities",
        bool_default: true,
        int: (0, 0, 0),
        dbl: (0.0, 0.0, 0.0),
        str_default: "",
    },
    Meta {
        type_: INT,
        advanced: true,
        name: "simplex_unscaled_solution_strategy",
        description: "Strategy for solving unscaled LP in simplex",
        bool_default: false,
        int: (0, 1, 2),
        dbl: (0.0, 0.0, 0.0),
        str_default: "",
    },
    Meta {
        type_: BOOL,
        advanced: true,
        name: "no_unnecessary_rebuild_refactor",
        description: "No unnecessary refactorization on simplex rebuild",
        bool_default: true,
        int: (0, 0, 0),
        dbl: (0.0, 0.0, 0.0),
        str_default: "",
    },
    Meta {
        type_: DOUBLE,
        advanced: true,
        name: "rebuild_refactor_solution_error_tolerance",
        description: "Tolerance on solution error when considering refactorization on simplex rebuild",
        bool_default: false,
        int: (0, 0, 0),
        dbl: (f64::NEG_INFINITY, 1e-08, f64::INFINITY),
        str_default: "",
    },
    Meta {
        type_: DOUBLE,
        advanced: true,
        name: "dual_steepest_edge_weight_error_tolerance",
        description: "Tolerance on dual steepest edge weight errors",
        bool_default: false,
        int: (0, 0, 0),
        dbl: (0.0, f64::INFINITY, f64::INFINITY),
        str_default: "",
    },
    Meta {
        type_: DOUBLE,
        advanced: true,
        name: "dual_steepest_edge_weight_log_error_threshold",
        description: "Threshold on dual steepest edge weight errors for Devex switch",
        bool_default: false,
        int: (0, 0, 0),
        dbl: (1.0, 10.0, f64::INFINITY),
        str_default: "",
    },
    Meta {
        type_: DOUBLE,
        advanced: true,
        name: "dual_simplex_cost_perturbation_multiplier",
        description: "Dual simplex cost perturbation multiplier: 0 => no perturbation",
        bool_default: false,
        int: (0, 0, 0),
        dbl: (0.0, 1.0, f64::INFINITY),
        str_default: "",
    },
    Meta {
        type_: DOUBLE,
        advanced: true,
        name: "primal_simplex_bound_perturbation_multiplier",
        description: "Primal simplex bound perturbation multiplier: 0 => no perturbation",
        bool_default: false,
        int: (0, 0, 0),
        dbl: (0.0, 1.0, f64::INFINITY),
        str_default: "",
    },
    Meta {
        type_: DOUBLE,
        advanced: true,
        name: "dual_simplex_pivot_growth_tolerance",
        description: "Dual simplex pivot growth tolerance",
        bool_default: false,
        int: (0, 0, 0),
        dbl: (9.9999999999999998e-13, 1.0000000000000001e-09, f64::INFINITY),
        str_default: "",
    },
    Meta {
        type_: DOUBLE,
        advanced: true,
        name: "presolve_pivot_threshold",
        description: "Matrix factorization pivot threshold for substitutions in presolve",
        bool_default: false,
        int: (0, 0, 0),
        dbl: (0.00080000000000000004, 0.01, 0.5),
        str_default: "",
    },
    Meta {
        type_: INT,
        advanced: true,
        name: "presolve_reduction_limit",
        description: "Limit on number of presolve reductions -1 => no limit",
        bool_default: false,
        int: (-1, -1, 2147483647),
        dbl: (0.0, 0.0, 0.0),
        str_default: "",
    },
    Meta {
        type_: INT,
        advanced: true,
        name: "restart_presolve_reduction_limit",
        description: "Limit on number of further presolve reductions on restart in MIP solver -1 => no limit, otherwise, must be positive",
        bool_default: false,
        int: (-1, -1, 2147483647),
        dbl: (0.0, 0.0, 0.0),
        str_default: "",
    },
    Meta {
        type_: INT,
        advanced: true,
        name: "presolve_rule_off",
        description: "Bit mask of presolve rules that are not allowed",
        bool_default: false,
        int: (0, 0, 2147483647),
        dbl: (0.0, 0.0, 0.0),
        str_default: "",
    },
    Meta {
        type_: INT,
        advanced: true,
        name: "presolve_rule_test",
        description: "Presolve rule to test - DEV only!",
        bool_default: false,
        int: (0, 0, 19),
        dbl: (0.0, 0.0, 0.0),
        str_default: "",
    },
    Meta {
        type_: BOOL,
        advanced: true,
        name: "presolve_rule_logging",
        description: "Log effectiveness of presolve rules for LP",
        bool_default: false,
        int: (0, 0, 0),
        dbl: (0.0, 0.0, 0.0),
        str_default: "",
    },
    Meta {
        type_: BOOL,
        advanced: true,
        name: "presolve_remove_slacks",
        description: "Remove slacks after presolve",
        bool_default: false,
        int: (0, 0, 0),
        dbl: (0.0, 0.0, 0.0),
        str_default: "",
    },
    Meta {
        type_: INT,
        advanced: true,
        name: "presolve_substitution_maxfillin",
        description: "Maximal fillin allowed for substitutions in presolve",
        bool_default: false,
        int: (0, 10, 2147483647),
        dbl: (0.0, 0.0, 0.0),
        str_default: "",
    },
    Meta {
        type_: DOUBLE,
        advanced: true,
        name: "factor_pivot_threshold",
        description: "Matrix factorization pivot threshold",
        bool_default: false,
        int: (0, 0, 0),
        dbl: (0.00080000000000000004, 0.10000000000000001, 0.5),
        str_default: "",
    },
    Meta {
        type_: DOUBLE,
        advanced: true,
        name: "factor_pivot_tolerance",
        description: "Matrix factorization pivot tolerance",
        bool_default: false,
        int: (0, 0, 0),
        dbl: (0.0, 1e-10, 1.0),
        str_default: "",
    },
    Meta {
        type_: DOUBLE,
        advanced: true,
        name: "start_crossover_tolerance",
        description: "Tolerance to be satisfied before IPM crossover will start",
        bool_default: false,
        int: (0, 0, 0),
        dbl: (9.9999999999999998e-13, 1e-08, f64::INFINITY),
        str_default: "",
    },
    Meta {
        type_: BOOL,
        advanced: true,
        name: "use_original_HFactor_logic",
        description: "Use original HFactor logic for sparse vs hyper-sparse TRANs",
        bool_default: true,
        int: (0, 0, 0),
        dbl: (0.0, 0.0, 0.0),
        str_default: "",
    },
    Meta {
        type_: BOOL,
        advanced: true,
        name: "less_infeasible_DSE_check",
        description: "Check whether LP is candidate for LiDSE",
        bool_default: true,
        int: (0, 0, 0),
        dbl: (0.0, 0.0, 0.0),
        str_default: "",
    },
    Meta {
        type_: BOOL,
        advanced: true,
        name: "less_infeasible_DSE_choose_row",
        description: "Use LiDSE if LP has right properties",
        bool_default: true,
        int: (0, 0, 0),
        dbl: (0.0, 0.0, 0.0),
        str_default: "",
    },
    Meta {
        type_: BOOL,
        advanced: true,
        name: "run_centring",
        description: "Perform centring steps or not",
        bool_default: false,
        int: (0, 0, 0),
        dbl: (0.0, 0.0, 0.0),
        str_default: "",
    },
    Meta {
        type_: INT,
        advanced: true,
        name: "max_centring_steps",
        description: "Maximum number of steps to use (default = 5) when computing the analytic centre",
        bool_default: false,
        int: (0, 5, 2147483647),
        dbl: (0.0, 0.0, 0.0),
        str_default: "",
    },
    Meta {
        type_: DOUBLE,
        advanced: true,
        name: "centring_ratio_tolerance",
        description: "Centring stops when the ratio max(x_j*s_j) / min(x_j*s_j) is below this tolerance (default = 100)",
        bool_default: false,
        int: (0, 0, 0),
        dbl: (0.0, 100.0, f64::INFINITY),
        str_default: "",
    },
];
